### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by stayallive** [thenpingme/thenpingme-laravel#16]
Hi Y'all,

I was wondering if you guys are planning to update this package to be compatible with PHP 8?

Edit: Nice of my to mistype the title... sorry for the confusion there 😉

**Comment by michaeldyrynda** [comment]
You can test with `2.x-dev` at the moment, but we’ve not tagged a release just yet

**Comment by michaeldyrynda** [comment]
[2.3.11](https://github.com/thenpingme/thenpingme-laravel/releases/tag/2.3.11) has been tagged with PHP 8 support
